#!/usr/bin/env bash
# setup.sh  —  Run this ONCE before python run.py
# Usage: bash setup.sh
set -euo pipefail

GREEN="\033[92m"; CYAN="\033[96m"; RED="\033[91m"; RESET="\033[0m"
ok()  { echo -e "${GREEN}  ✔  $*${RESET}"; }
info(){ echo -e "${CYAN}  ▶  $*${RESET}"; }
err() { echo -e "${RED}  ✘  $*${RESET}"; exit 1; }

# ── 1. Fabric PATH ───────────────────────────────────────────────────────────
for d in \
    "$HOME/fabric-samples/bin" \
    "$HOME/go/src/github.com/hyperledger/fabric-samples/bin" \
    "/usr/local/fabric/bin"; do
    if [ -d "$d" ]; then
        export PATH="$d:$PATH"
        ok "Fabric bin found: $d"
        break
    fi
done

which peer   >/dev/null 2>&1 || err "'peer' not found — install Fabric binaries first:
  curl -sSL https://bit.ly/2ysbOFE | bash -s -- 2.5.0 1.5.7"
which cryptogen  >/dev/null 2>&1 || err "'cryptogen' not found"
which configtxgen>/dev/null 2>&1 || err "'configtxgen' not found"
ok "Fabric binaries OK"

# ── 2. .env ───────────────────────────────────────────────────────────────────
if [ ! -f .env ]; then
    cp .env.example .env
    ok ".env created from .env.example"
else
    ok ".env already exists — skipping copy"
fi

# Derive cert paths from crypto-config (may not exist yet — run.py generates them)
# These will be regenerated by run.py; we set them so the config check passes.
PEER_ORG="crypto-config/peerOrganizations/org1.example.com"
ADMIN_MSP="$PEER_ORG/users/Admin@org1.example.com/msp"
PEER0_TLS="$PEER_ORG/peers/peer0.org1.example.com/tls/ca.crt"
PEER0_SIGN_CERT="$PEER_ORG/peers/peer0.org1.example.com/msp/signcerts/peer0.org1.example.com-cert.pem"
PEER0_SIGN_KEY="$PEER_ORG/peers/peer0.org1.example.com/msp/keystore/priv_sk"

# Write all required vars into .env (idempotent — only adds if not already set)
add_env() {
    local key="$1" val="$2"
    if grep -q "^${key}=" .env 2>/dev/null; then
        # already set — overwrite to ensure correct value
        sed -i "s|^${key}=.*|${key}=${val}|" .env
    else
        echo "${key}=${val}" >> .env
    fi
}

add_env KAFKA_BOOTSTRAP_SERVERS  "localhost:9092"
add_env IPFS_API_URL              "http://localhost:5001"
add_env REDIS_URL                 "redis://localhost:6379/0"
add_env FABRIC_TLS_CERT           "./$PEER0_TLS"
add_env FABRIC_SIGN_CERT          "./$PEER0_SIGN_CERT"
add_env FABRIC_SIGN_KEY           "./$PEER0_SIGN_KEY"
add_env FABRIC_MSP_ID             "Org1MSP"
add_env FABRIC_PEER_ENDPOINT      "localhost:7051"
add_env FABRIC_ORDERER_ENDPOINT   "localhost:7050"
add_env LIVE_MODE                 "1"

ok ".env fully configured"

# ── 3. Export into current shell ──────────────────────────────────────────────
set -o allexport
# shellcheck disable=SC1091
source .env
set +o allexport
ok "Environment variables exported into current shell"

# ── 4. Python venv ────────────────────────────────────────────────────────────
if [ ! -d .venv ]; then
    info "Creating Python venv ..."
    python3 -m venv .venv
    ok ".venv created"
else
    ok ".venv already exists"
fi

source .venv/bin/activate
pip install --upgrade pip -q

for req in $(find services -name requirements.txt); do
    info "Installing $req ..."
    pip install -r "$req" -q
done

pip install requests -q   # needed by run.py benchmark
ok "All Python dependencies installed"

# ── 5. Summary ────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}══════════════════════════════════════════════════"
echo -e "  Setup complete.  Run the stack with:"
echo -e ""
echo -e "    source .env && python run.py"
echo -e ""
echo -e "  Or in one line:"
echo -e ""
echo -e "    bash setup.sh && source .env && python run.py"
echo -e "══════════════════════════════════════════════════${RESET}"
